[INFO     2015-03-04 12:41:33,048 bulkloader.py] Logging to bulkloader-log-20150304.124133
[INFO     2015-03-04 12:41:33,049 bulkloader.py] Throttling transfers:
[INFO     2015-03-04 12:41:33,049 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2015-03-04 12:41:33,049 bulkloader.py] HTTP connections: 8/second
[INFO     2015-03-04 12:41:33,049 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2015-03-04 12:41:33,049 bulkloader.py] Batch Size: 10
[INFO     2015-03-04 12:41:33,066 bulkloader.py] Opening database: bulkloader-progress-20150304.124133.sql3
[DEBUG    2015-03-04 12:41:33,093 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,095 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,096 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,096 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,098 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,098 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,099 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,100 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,101 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,102 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: started
[DEBUG    2015-03-04 12:41:33,102 bulkloader.py] Configuring remote_api. url_path = /remote_api, servername = missy-go.appspot.com
[DEBUG    2015-03-04 12:41:33,139 bulkloader.py] Bulkloader using app_id: missy-go
[INFO     2015-03-04 12:41:33,139 bulkloader.py] Connecting to missy-go.appspot.com/remote_api
[DEBUG    2015-03-04 12:41:42,567 bulkloader.py] [Thread-11] ProgressTrackerThread: started
[DEBUG    2015-03-04 12:41:42,569 bulkloader.py] [Thread-12] DataSourceThread: started
[INFO     2015-03-04 12:41:42,569 bulkloader.py] Starting import; maximum 10 entities per post
[DEBUG    2015-03-04 12:41:42,595 bulkloader.py] [Thread-12] DataSourceThread: exiting
[DEBUG    2015-03-04 12:41:42,607 bulkloader.py] Waiting for worker threads to finish...
[DEBUG    2015-03-04 12:41:42,607 adaptive_thread_pool.py] [WorkerThread-0] Got work item [1-10]
[ERROR    2015-03-04 12:41:43,280 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread:
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 172, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 753, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 924, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1452, in PostEntities
    datastore.Put(entities)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/datastore.py", line 605, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 899, in get_result
    results = self.__rpcs[0].get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1827, in __put_hook
    self.check_rpc_success(rpc)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1342, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: app s~missy-go cannot access app missy-go's data
[DEBUG    2015-03-04 12:41:43,289 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: exiting
[INFO     2015-03-04 12:41:43,289 adaptive_thread_pool.py] [WorkerThread-1] Backing off due to errors: 1.0 seconds
[INFO     2015-03-04 12:41:43,612 bulkloader.py] An error occurred. Shutting down...
[DEBUG    2015-03-04 12:41:43,613 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,615 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,615 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,615 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,615 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,615 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,615 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,616 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,617 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,617 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,791 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: exiting
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[ERROR    2015-03-04 12:41:43,792 adaptive_thread_pool.py] Error in WorkerThread-0: app s~missy-go cannot access app missy-go's data
[DEBUG    2015-03-04 12:41:43,793 adaptive_thread_pool.py] Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/adaptive_thread_pool.py", line 172, in WorkOnItems
    status, instruction = item.PerformWork(self.__thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 753, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 924, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1452, in PostEntities
    datastore.Put(entities)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/datastore.py", line 605, in Put
    return PutAsync(entities, **kwargs).get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 899, in get_result
    results = self.__rpcs[0].get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1827, in __put_hook
    self.check_rpc_success(rpc)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 1342, in check_rpc_success
    raise _ToDatastoreError(err)
BadRequestError: app s~missy-go cannot access app missy-go's data

[DEBUG    2015-03-04 12:41:43,793 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2015-03-04 12:41:43,819 bulkloader.py] [Thread-11] ProgressTrackerThread: exiting
[DEBUG    2015-03-04 12:41:43,842 bulkloader.py] ... done.
[INFO     2015-03-04 12:41:43,843 bulkloader.py] 65 entities total, 0 previously transferred
[INFO     2015-03-04 12:41:43,843 bulkloader.py] 0 entities (13246 bytes) transferred in 10.8 seconds
[INFO     2015-03-04 12:41:43,843 bulkloader.py] Some entities not successfully transferred
